theme: jekyll-theme-leap-day
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=NHBvcHQxZ2hkb2s1N2gxa2RodXNqMHYyYjkgbXVyb3NsYXYuaWxuaWNraXVAbQ&amp;tmsrc=muroslav.ilnickiu%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_uk.gif"></a>
